services:
  postgres:
    image: postgres:16
    container_name: sniff-n-frolic-ecommerce
    restart: unless-stopped
    environment:
      POSTGRES_USER: snf
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sniff_catalog
    ports:
      - "5433:5432"
    volumes:
      - snf_postgres_data:/var/lib/postgresql/data

volumes:
  snf_postgres_data:


# Access Database
# docker exec -it sniff-n-frolic-ecommerce psql -U snf -d sniff_catalog