// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/[lang]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/about">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/cart">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/category/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/checkout/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/checkout/success">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/checkout/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/cookie-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/cookie-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/cookie-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/how-to-buy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/how-to-buy">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/how-to-buy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/order/confirm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/order/confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/order/confirm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/products/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/products/[slug]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/products/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/products">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/[lang]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[lang]/search">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/categories">> = Specific
  const handler = {} as typeof import("../../../src/app/api/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checkout/complete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout/complete">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checkout/complete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../../src/app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/[lang]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[lang]">> = Specific
  const handler = {} as typeof import("../../../src/app/[lang]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
